// Code generated by "stringer -type EventType constants.go structs.go"; DO NOT EDIT

package zetcd

import "fmt"

const _EventType_name = "EventNodeCreatedEventNodeDeletedEventNodeDataChangedEventNodeChildrenChanged"

var _EventType_index = [...]uint8{0, 16, 32, 52, 76}

func (i EventType) String() string {
	i -= 1
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return fmt.Sprintf("EventType(%d)", i+1)
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
